baseURL = "https://fundyourinternet.org/"
languageCode = "en-GB"
title = "Fund Your Internet"
disableKinds = ["taxonomy"]

[params]
  description = "A practical guide to sustaining the things you rely on online."
  repository = "https://github.com/fundyourinternet/fundyourinternet.org"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false

[menus]
  [[menus.main]]
    name = "One Thing"
    url = "/"
    weight = -1
  [[menus.main]]
    name = "The Old Way"
    pageRef = "/the-old-way"
    weight = 1
  [[menus.main]]
    name = "A New Way"
    pageRef = "/a-new-way"
    weight = 2
  [[menus.main]]
    name = "The Evidence"
    pageRef = "/the-evidence"
    weight = 3
